# Generated by Django 6.0.6 on 2026-06-12 20:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_subscriptioninvoice'),
        ('purchasing', '0002_supplierreturn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('part_received', 'Partially received'), ('received', 'Received'), ('discrepancy', 'Receipt discrepancy'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='draft', max_length=24),
        ),
        migrations.CreateModel(
            name='PurchaseDiscrepancy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.CharField(max_length=40)),
                ('expected_quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('accepted_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('damaged_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('missing_quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('resolution', models.CharField(blank=True, max_length=40)),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='discrepancies', to='purchasing.purchaseorderline')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'number'), name='unique_purchase_discrepancy_number')],
            },
        ),
    ]
