# Generated by Django 5.0.14 on 2026-07-19 16:59

import apps.purchasing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0003_alter_purchaseorder_status_purchasediscrepancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='attachment',
            field=models.FileField(blank=True, max_length=500, upload_to=apps.purchasing.models.purchase_attachment_upload_path),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_reference',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
