# Generated by Django 5.0.14 on 2026-07-19 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_purchaseorder_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='extracted_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='extraction_status',
            field=models.CharField(choices=[('not_requested', 'Not requested'), ('extracted', 'Extracted'), ('manual_review', 'Manual review required'), ('failed', 'Failed')], default='not_requested', max_length=24),
        ),
    ]
