# Generated by Django 6.0.6 on 2026-08-15 00:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('organizations', '0009_agentprofile_verification_notes'),
        ('purchasing', '0006_purchasereceipt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['organization', 'status', 'ordered_on'], name='po_org_st_date'),
        ),
    ]
