# Generated by Django 6.0.6 on 2026-06-13 11:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_subscriptioninvoice'),
        ('sales', '0002_salereturn'),
    ]

    operations = [
        migrations.AddField(
            model_name='salereturn',
            name='outcome',
            field=models.CharField(choices=[('refund', 'Refund'), ('exchange', 'Exchange'), ('store_credit', 'Store credit'), ('repair', 'Send for repair')], default='refund', max_length=24),
        ),
        migrations.CreateModel(
            name='SaleReturnLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('disposition', models.CharField(choices=[('restock', 'Return to available stock'), ('damaged', 'Damaged / quarantine'), ('repair', 'Warranty repair')], default='restock', max_length=24)),
                ('refundable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('sale_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='sales.saleline')),
                ('sale_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.salereturn')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('sale_return', 'sale_line'), name='unique_sale_line_per_return')],
            },
        ),
    ]
