# Generated by Django 5.0.14 on 2026-07-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salereturn_outcome_salereturnline'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='credit_agency',
            field=models.CharField(blank=True, choices=[('', 'Not applicable'), ('watu', 'Watu Credit'), ('mkopa', 'M-Kopa'), ('onfon', 'OnFon'), ('mogo', 'Mogo'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_national_id',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='sale',
            name='next_of_kin_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='sale',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='sale',
            name='sale_channel',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit')], default='cash', max_length=20),
        ),
    ]
