# Generated by Django 5.0.14 on 2026-07-11 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('organizations', '0005_alter_organization_options'),
        ('pos', '0003_possession_unique_open_pos_session_per_cashier_location'),
        ('sales', '0004_sale_credit_agency_sale_customer_national_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'draft')), fields=('organization', 'session', 'created_by'), name='unique_active_cart_per_session_user'),
        ),
    ]
