# Generated by Django 6.0.6 on 2026-08-15 00:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('organizations', '0009_agentprofile_verification_notes'),
        ('pos', '0005_offlineinvoicequeue_device_id_and_more'),
        ('sales', '0005_sale_unique_active_cart_per_session_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['organization', 'location', 'status', 'completed_at'], name='sale_org_loc_st_done'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['organization', 'customer', 'completed_at'], name='sale_org_cust_done'),
        ),
    ]
