# Generated by Codex on 2026-07-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_recoverycode_usersession"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_demo_account",
            field=models.BooleanField(
                default=False,
                help_text="Allows privacy-safe demo onboarding tools. Keep disabled for live client accounts.",
            ),
        ),
    ]
