# Generated by Django 6.0.6 on 2026-08-15 00:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_agentprofile_verification_notes'),
        ('transfers', '0003_transfertransition'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stocktransfer',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='tr_org_st_created'),
        ),
    ]
