# Generated by Django 6.0.6 on 2026-06-12 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('commissions', '0001_initial'),
        ('organizations', '0002_announcement_organizationsetting'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commissionaccrual',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='commissions', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='commissionrule',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='catalog.product'),
        ),
        migrations.AddField(
            model_name='commissionaccrual',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='commissions.commissionrule'),
        ),
    ]
