# Generated by Django 6.0.6 on 2026-06-12 19:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commissions', '0002_initial'),
        ('organizations', '0003_subscriptioninvoice'),
        ('sales', '0002_salereturn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='commissionaccrual',
            constraint=models.UniqueConstraint(fields=('organization', 'sale', 'agent', 'rule'), name='unique_commission_accrual'),
        ),
    ]
