# Generated by Django 5.0.14 on 2026-07-26 21:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('organizations', '0009_agentprofile_verification_notes'),
        ('sales', '0005_sale_unique_active_cart_per_session_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FiscalDevice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('etims', 'KRA eTIMS')], default='etims', max_length=32)),
                ('mode', models.CharField(choices=[('oscu', 'OSCU'), ('vscu', 'VSCU')], default='oscu', max_length=16)),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=16)),
                ('status', models.CharField(choices=[('not_configured', 'Not configured'), ('sandbox_testing', 'Sandbox testing'), ('ready_for_production', 'Ready for production'), ('active', 'Active'), ('suspended', 'Suspended'), ('failed', 'Failed / needs attention')], default='not_configured', max_length=32)),
                ('receipt_policy', models.CharField(choices=[('standard_only', 'Standard receipt only'), ('standard_and_etims', 'Standard receipt plus eTIMS'), ('etims_required', 'Require eTIMS before final tax receipt')], default='standard_and_etims', max_length=32)),
                ('taxpayer_pin', models.CharField(max_length=32)),
                ('branch_office_id', models.CharField(help_text='KRA branch office ID / bhfId.', max_length=32)),
                ('device_serial', models.CharField(blank=True, max_length=80)),
                ('device_name', models.CharField(blank=True, max_length=120)),
                ('last_tested_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('activated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='activated_fiscal_devices', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_devices', to='organizations.company')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_devices', to='organizations.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
            ],
            options={
                'ordering': ('organization', 'provider', 'branch_office_id'),
            },
        ),
        migrations.CreateModel(
            name='FiscalDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('etims', 'KRA eTIMS')], default='etims', max_length=32)),
                ('document_type', models.CharField(choices=[('sale', 'Sale tax invoice'), ('credit_note', 'Credit note')], max_length=24)),
                ('status', models.CharField(choices=[('not_required', 'Not required'), ('pending', 'Pending'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('failed', 'Failed'), ('dead', 'Dead letter')], default='pending', max_length=24)),
                ('internal_number', models.CharField(max_length=48)),
                ('receipt_type_code', models.CharField(blank=True, max_length=8)),
                ('transaction_type_code', models.CharField(blank=True, max_length=8)),
                ('etims_invoice_number', models.CharField(blank=True, max_length=120)),
                ('etims_control_code', models.CharField(blank=True, max_length=120)),
                ('etims_signature', models.CharField(blank=True, max_length=255)),
                ('qr_payload', models.TextField(blank=True)),
                ('payload_snapshot', models.JSONField(blank=True, default=dict)),
                ('response_snapshot', models.JSONField(blank=True, default=dict)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='integrations.fiscaldevice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_documents', to='sales.sale')),
                ('sale_return', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_documents', to='sales.salereturn')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FiscalDocumentLine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255)),
                ('item_code', models.CharField(max_length=80)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('imei_or_serial', models.CharField(blank=True, max_length=120)),
                ('tax_type_code', models.CharField(default='B', max_length=12)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='integrations.fiscaldocument')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='fiscaldevice',
            constraint=models.UniqueConstraint(fields=('organization', 'provider', 'branch_office_id', 'environment'), name='unique_fiscal_device_branch_environment'),
        ),
        migrations.AddConstraint(
            model_name='fiscaldocument',
            constraint=models.UniqueConstraint(condition=models.Q(('sale__isnull', False)), fields=('organization', 'sale', 'document_type'), name='unique_fiscal_document_per_sale_type'),
        ),
        migrations.AddConstraint(
            model_name='fiscaldocument',
            constraint=models.UniqueConstraint(condition=models.Q(('sale_return__isnull', False)), fields=('organization', 'sale_return', 'document_type'), name='unique_fiscal_document_per_return_type'),
        ),
    ]
