# Generated by Django 6.0.6 on 2026-08-15 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_fiscaldevice_fiscaldocument_fiscaldocumentline_and_more'),
        ('organizations', '0009_agentprofile_verification_notes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='integrationevent',
            index=models.Index(fields=['status', 'next_retry_at', 'provider'], name='int_status_retry_prov'),
        ),
        migrations.AddIndex(
            model_name='integrationevent',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='int_org_st_created'),
        ),
    ]
