CSV_FORMULA_PREFIXES = ("=", "+", "-", "@", "\t", "\r")


def safe_csv_cell(value):
    if value is None:
        return ""
    text = str(value)
    if text.startswith(CSV_FORMULA_PREFIXES):
        return f"'{text}"
    return text


def safe_csv_row(values):
    return [safe_csv_cell(value) for value in values]


def _escape_pdf_text(value):
    text = safe_csv_cell(value)
    return text.replace("\\", "\\\\").replace("(", "\\(").replace(")", "\\)")


def build_simple_pdf(*, title, headers, rows, limit=80):
    rows = list(rows)
    lines = [title, ""] + [" | ".join(safe_csv_row(headers))]
    for row in rows[:limit]:
        lines.append(" | ".join(safe_csv_row(row)))
    if len(rows) > limit:
        lines.append(f"... truncated to first {limit} rows")

    content_lines = ["BT", "/F1 9 Tf", "36 806 Td", "12 TL"]
    for line in lines[:62]:
        text = _escape_pdf_text(str(line)[:145])
        content_lines.append(f"({text}) Tj")
        content_lines.append("T*")
    content_lines.append("ET")
    stream = "\n".join(content_lines).encode("latin-1", "replace")
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>",
        b"<< /Length " + str(len(stream)).encode("ascii") + b" >>\nstream\n" + stream + b"\nendstream",
    ]
    pdf = bytearray(b"%PDF-1.4\n")
    offsets = [0]
    for index, obj in enumerate(objects, start=1):
        offsets.append(len(pdf))
        pdf.extend(f"{index} 0 obj\n".encode("ascii"))
        pdf.extend(obj)
        pdf.extend(b"\nendobj\n")
    xref_offset = len(pdf)
    pdf.extend(f"xref\n0 {len(objects) + 1}\n".encode("ascii"))
    pdf.extend(b"0000000000 65535 f \n")
    for offset in offsets[1:]:
        pdf.extend(f"{offset:010d} 00000 n \n".encode("ascii"))
    pdf.extend(
        f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref_offset}\n%%EOF\n".encode("ascii")
    )
    return bytes(pdf)


def build_statement_pdf(*, title, organization, contact, summary, headers, rows, limit=70):
    rows = list(rows)
    lines = [
        "MobiPOS",
        organization.name,
        f"{title}",
        f"Contact: {contact.name}",
        f"Type: {contact.get_contact_type_display()}",
    ]
    if contact.tax_number:
        lines.append(f"Tax number / KRA PIN: {contact.tax_number}")
    if contact.phone_number or contact.email:
        lines.append(f"Contact details: {contact.phone_number or '-'} {contact.email or ''}".strip())
    lines.extend(
        [
            "",
            "Summary",
            f"Sales: KES {summary['sales_total']}",
            f"Payments: KES {summary['payments_total']}",
            f"Receivable balance: KES {summary['receivable_total']}",
            f"Payable balance: KES {summary['payable_total']}",
            "",
            "Statement Lines",
            " | ".join(safe_csv_row(headers)),
        ]
    )
    for row in rows[:limit]:
        lines.append(" | ".join(safe_csv_row(row)))
    if len(rows) > limit:
        lines.append(f"... truncated to first {limit} rows")
    lines.extend(["", "Generated by MobiPOS."])

    content_lines = ["BT", "/F1 16 Tf", "36 806 Td", "18 TL"]
    first_line = True
    for line in lines[:58]:
        if first_line:
            content_lines.append(f"({_escape_pdf_text(str(line)[:120])}) Tj")
            content_lines.append("T*")
            content_lines.append("/F1 10 Tf")
            content_lines.append("12 TL")
            first_line = False
            continue
        text = _escape_pdf_text(str(line)[:145])
        content_lines.append(f"({text}) Tj")
        content_lines.append("T*")
    content_lines.append("ET")
    stream = "\n".join(content_lines).encode("latin-1", "replace")
    objects = [
        b"<< /Type /Catalog /Pages 2 0 R >>",
        b"<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
        b"<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 842] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>",
        b"<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold >>",
        b"<< /Length " + str(len(stream)).encode("ascii") + b" >>\nstream\n" + stream + b"\nendstream",
    ]
    pdf = bytearray(b"%PDF-1.4\n")
    offsets = [0]
    for index, obj in enumerate(objects, start=1):
        offsets.append(len(pdf))
        pdf.extend(f"{index} 0 obj\n".encode("ascii"))
        pdf.extend(obj)
        pdf.extend(b"\nendobj\n")
    xref_offset = len(pdf)
    pdf.extend(f"xref\n0 {len(objects) + 1}\n".encode("ascii"))
    pdf.extend(b"0000000000 65535 f \n")
    for offset in offsets[1:]:
        pdf.extend(f"{offset:010d} 00000 n \n".encode("ascii"))
    pdf.extend(
        f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\nstartxref\n{xref_offset}\n%%EOF\n".encode("ascii")
    )
    return bytes(pdf)
