from io import BytesIO
import textwrap
from decimal import Decimal

from reportlab.lib.pagesizes import A4
from reportlab.pdfgen import canvas


CSV_FORMULA_PREFIXES = ("=", "+", "-", "@", "\t", "\r")


def safe_csv_cell(value):
    if value is None:
        return ""
    text = str(value)
    is_numeric = isinstance(value, (int, float, Decimal)) and not isinstance(value, bool)
    if not is_numeric and text.startswith(CSV_FORMULA_PREFIXES):
        return f"'{text}"
    return text


def safe_csv_row(values):
    return [safe_csv_cell(value) for value in values]


def _build_multipage_pdf(lines):
    stream = BytesIO()
    document = canvas.Canvas(stream, pagesize=A4, pageCompression=0)
    width, height = A4
    y = height - 42
    page_number = 1

    def start_page():
        nonlocal y
        document.setFont("Helvetica", 9)
        y = height - 42

    start_page()
    for raw_line in lines:
        wrapped_lines = textwrap.wrap(str(raw_line), width=118, break_long_words=True) or [""]
        for line in wrapped_lines:
            if y < 42:
                document.setFont("Helvetica", 8)
                document.drawRightString(width - 36, 24, f"Page {page_number}")
                document.showPage()
                page_number += 1
                start_page()
            document.drawString(36, y, line.encode("latin-1", "replace").decode("latin-1"))
            y -= 12
    document.setFont("Helvetica", 8)
    document.drawRightString(width - 36, 24, f"Page {page_number}")
    document.save()
    return stream.getvalue()


def build_simple_pdf(*, title, headers, rows, limit=None):
    lines = [title, "", " | ".join(safe_csv_row(headers))]
    lines.extend(" | ".join(safe_csv_row(row)) for row in rows)
    return _build_multipage_pdf(lines)


def build_statement_pdf(*, title, organization, contact, summary, headers, rows, limit=None):
    lines = [
        "MobiPOS",
        organization.name,
        f"{title}",
        f"Contact: {contact.name}",
        f"Type: {contact.get_contact_type_display()}",
    ]
    if contact.tax_number:
        lines.append(f"Tax number / KRA PIN: {contact.tax_number}")
    if contact.phone_number or contact.email:
        lines.append(f"Contact details: {contact.phone_number or '-'} {contact.email or ''}".strip())
    lines.extend(
        [
            "",
            "Summary",
            f"Sales: KES {summary['sales_total']}",
            f"Payments: KES {summary['payments_total']}",
            f"Receivable balance: KES {summary['receivable_total']}",
            f"Payable balance: KES {summary['payable_total']}",
            "",
            "Statement Lines",
            " | ".join(safe_csv_row(headers)),
        ]
    )
    for row in rows:
        lines.append(" | ".join(safe_csv_row(row)))
    lines.extend(["", "Generated by MobiPOS."])
    return _build_multipage_pdf(lines)
