# Generated by Django 5.0.14 on 2026-07-11 15:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('organizations', '0004_invitation'),
        ('payments', '0003_refund'),
        ('sales', '0004_sale_credit_agency_sale_customer_national_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_reference', ''), _negated=True), fields=('organization', 'method', 'provider_reference'), name='unique_payment_provider_reference_per_org_method'),
        ),
    ]
