# Generated by Django 6.0.6 on 2026-08-15 00:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('organizations', '0009_agentprofile_verification_notes'),
        ('payments', '0005_payment_verification_metadata'),
        ('sales', '0005_sale_unique_active_cart_per_session_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['organization', 'sale', 'status', 'received_at'], name='pay_org_sale_st_recv'),
        ),
    ]
