# Generated by Django 6.0.6 on 2026-06-12 18:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('organizations', '0002_announcement_organizationsetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockUnit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=120)),
                ('secondary_serial', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('expected', 'Expected'), ('available', 'Available'), ('reserved', 'Reserved'), ('in_transfer', 'In transfer'), ('sold', 'Sold'), ('returned', 'Returned'), ('damaged', 'Damaged'), ('warranty_repair', 'Warranty repair'), ('written_off', 'Written off')], default='expected', max_length=24)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('warranty_expires_on', models.DateField(blank=True, null=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_units', to='organizations.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_units', to='catalog.product')),
            ],
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('opening', 'Opening balance'), ('purchase_receipt', 'Purchase receipt'), ('supplier_return', 'Supplier return'), ('transfer_dispatch', 'Transfer dispatch'), ('transfer_receipt', 'Transfer receipt'), ('sale', 'Sale'), ('customer_return', 'Customer return'), ('adjustment', 'Adjustment'), ('repair_issue', 'Repair issue'), ('reversal', 'Reversal')], max_length=30)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reference_type', models.CharField(blank=True, max_length=80)),
                ('reference_id', models.CharField(blank=True, max_length=120)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='organizations.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='catalog.product')),
                ('reversed_movement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.stockmovement')),
                ('stock_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stockunit')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=14)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='organizations.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='catalog.product')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('organization', 'product', 'location'), name='unique_stock_balance')],
            },
        ),
        migrations.AddConstraint(
            model_name='stockunit',
            constraint=models.UniqueConstraint(fields=('organization', 'serial_number'), name='unique_serial_per_org'),
        ),
    ]
