# Generated by Django 5.0.14 on 2026-07-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
        ('inventory', '0002_alter_stockmovement_reversed_movement_and_more'),
        ('organizations', '0005_alter_organization_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stockunit',
            constraint=models.UniqueConstraint(condition=models.Q(('secondary_serial', ''), _negated=True), fields=('organization', 'secondary_serial'), name='unique_secondary_serial_per_org'),
        ),
        migrations.AddConstraint(
            model_name='stockunit',
            constraint=models.CheckConstraint(check=models.Q(('secondary_serial', ''), models.Q(('serial_number', models.F('secondary_serial')), _negated=True), _connector='OR'), name='stockunit_primary_secondary_differ'),
        ),
    ]
