# Generated by Django 5.0.14 on 2026-08-13 15:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stockunit_unique_secondary_serial_per_org_and_more'),
        ('operations', '0008_alter_approvalrequest_options_and_more'),
        ('organizations', '0009_agentprofile_verification_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgedStockAction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('transfer', 'Transfer to a faster branch'), ('discount', 'Run a discount or promotion'), ('supplier_return', 'Return to supplier'), ('campaign', 'Add to sales campaign'), ('write_off', 'Write off or retire'), ('other', 'Other action')], max_length=40)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20)),
                ('reason', models.TextField()),
                ('next_step', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approval', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='aged_stock_actions', to='operations.approvalrequest')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_aged_stock_actions', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='completed_aged_stock_actions', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('proposed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proposed_aged_stock_actions', to=settings.AUTH_USER_MODEL)),
                ('stock_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aged_stock_actions', to='inventory.stockunit')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
