# Generated by Django 5.0.14 on 2026-08-14 21:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_agedstockaction'),
        ('organizations', '0009_agentprofile_verification_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='agedstockaction',
            name='execution_result',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='agedstockaction',
            name='proposal',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='StockUnitOffer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offer_type', models.CharField(choices=[('discount', 'Discount'), ('campaign', 'Campaign')], max_length=20)),
                ('name', models.CharField(max_length=160)),
                ('promotional_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('starts_on', models.DateField()),
                ('ends_on', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('aged_stock_action', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='offer', to='inventory.agedstockaction')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('stock_unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='inventory.stockunit')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
