# Generated by Django 6.0.6 on 2026-08-15 00:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_image_product_image_url'),
        ('inventory', '0005_aged_stock_execution'),
        ('organizations', '0009_agentprofile_verification_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', 'stock_unit', 'created_at'], name='inv_sm_org_su_ct'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['organization', 'product', 'location', 'created_at'], name='inv_sm_org_pr_loc_ct'),
        ),
        migrations.AddIndex(
            model_name='stockunit',
            index=models.Index(fields=['organization', 'status', 'location', 'product'], name='inv_su_org_st_loc_pr'),
        ),
        migrations.AddIndex(
            model_name='stockunit',
            index=models.Index(fields=['organization', 'product', 'location', 'created_at'], name='inv_su_org_pr_loc_ct'),
        ),
    ]
