# Generated by Django 6.0.6 on 2026-06-12 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receivable',
            name='sale',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='receivable', to='sales.sale'),
        ),
    ]
