# Generated by Django 6.0.6 on 2026-06-12 20:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('operations', '0003_approvalrequest'),
        ('organizations', '0003_subscriptioninvoice'),
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payable',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('outstanding_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('due_on', models.DateField()),
                ('is_settled', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('purchase_order', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payable', to='purchasing.purchaseorder')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payables', to='contacts.contact')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
