# Generated by Django 6.0.6 on 2026-06-12 20:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_payable'),
        ('organizations', '0003_subscriptioninvoice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='approvalrequest',
            constraint=models.UniqueConstraint(fields=('organization', 'request_type', 'target_type', 'target_id'), name='unique_approval_request_target'),
        ),
    ]
