# Generated by Django 6.0.6 on 2026-06-13 11:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_approvalrequest_unique_approval_request_target'),
        ('organizations', '0003_subscriptioninvoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivableInstallment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('due_on', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('part_paid', 'Partially paid'), ('paid', 'Paid'), ('overdue', 'Overdue')], default='pending', max_length=20)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('receivable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='operations.receivable')),
            ],
            options={
                'ordering': ('sequence',),
                'constraints': [models.UniqueConstraint(fields=('receivable', 'sequence'), name='unique_receivable_installment_sequence')],
            },
        ),
    ]
