# Generated by Django 6.0.6 on 2026-06-13 11:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0006_receivableinstallment'),
        ('organizations', '0004_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_requests', to='organizations.branch'),
        ),
        migrations.CreateModel(
            name='ApprovalPolicy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('request_type', models.CharField(max_length=80)),
                ('minimum_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('require_separate_approver', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('approver_roles', models.ManyToManyField(blank=True, related_name='approval_policies', to='organizations.role')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approval_policies', to='organizations.branch')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
            ],
            options={
                'ordering': ('request_type', 'minimum_amount'),
            },
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='requests', to='operations.approvalpolicy'),
        ),
        migrations.AddConstraint(
            model_name='approvalpolicy',
            constraint=models.UniqueConstraint(fields=('organization', 'name'), name='unique_approval_policy_name_per_org'),
        ),
    ]
