# Generated by Django 5.0.14 on 2026-07-11 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0007_approvalrequest_amount_approvalrequest_branch_and_more'),
        ('organizations', '0005_alter_organization_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvalrequest',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='receivableinstallment',
            options={'ordering': ('schedule_version', 'sequence')},
        ),
        migrations.RemoveConstraint(
            model_name='approvalrequest',
            name='unique_approval_request_target',
        ),
        migrations.RemoveConstraint(
            model_name='receivableinstallment',
            name='unique_receivable_installment_sequence',
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='decision_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='policy_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='previous_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='newer_requests', to='operations.approvalrequest'),
        ),
        migrations.AddField(
            model_name='receivableinstallment',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='receivableinstallment',
            name='replaced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='receivableinstallment',
            name='schedule_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='receivableinstallment',
            constraint=models.UniqueConstraint(fields=('receivable', 'schedule_version', 'sequence'), name='unique_receivable_installment_version_sequence'),
        ),
    ]
