# Generated by Django 6.0.6 on 2026-08-15 00:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0009_payable_credit_balance_payablepayment'),
        ('organizations', '0009_agentprofile_verification_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['organization', 'status', 'created_at'], name='appr_org_st_created'),
        ),
        migrations.AddIndex(
            model_name='approvalrequest',
            index=models.Index(fields=['organization', 'request_type', 'status', 'created_at'], name='appr_org_type_st_ct'),
        ),
    ]
