# Generated by Django 6.0.6 on 2026-08-14 21:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def backfill_expense_approvals(apps, schema_editor):
    Expense = apps.get_model("expenses", "Expense")
    ApprovalRequest = apps.get_model("operations", "ApprovalRequest")
    for expense in Expense.objects.select_related("requested_by", "approved_by").iterator():
        if expense.status == "submitted":
            approval_status = "pending"
            decided_by_id = None
            decided_at = None
            decision_notes = ""
        elif expense.status in {"approved", "paid"} and expense.approved_by_id:
            approval_status = "approved"
            decided_by_id = expense.approved_by_id
            decided_at = expense.updated_at
            decision_notes = "Migrated from the existing approved expense record."
        else:
            continue
        approval = ApprovalRequest.objects.create(
            organization_id=expense.organization_id,
            request_type="expense",
            target_type="expenses.Expense",
            target_id=str(expense.id),
            reason=f"{expense.category}: {expense.description}",
            branch_id=expense.branch_id,
            amount=expense.amount,
            status=approval_status,
            requested_by_id=expense.requested_by_id,
            decided_by_id=decided_by_id,
            decided_at=decided_at,
            decision_notes=decision_notes,
        )
        expense.approval_id = approval.id
        expense.save(update_fields=["approval"])


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('operations', '0008_alter_approvalrequest_options_and_more'),
        ('organizations', '0009_agentprofile_verification_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpensePayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('card', 'Card'), ('bank', 'Bank transfer')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField()),
            ],
            options={
                'ordering': ('-paid_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AddField(
            model_name='expense',
            name='approval',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_expense', to='operations.approvalrequest'),
        ),
        migrations.AddConstraint(
            model_name='expense',
            constraint=models.UniqueConstraint(fields=('organization', 'number'), name='unique_expense_number_per_org'),
        ),
        migrations.AddField(
            model_name='expensepayment',
            name='expense',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='expenses.expense'),
        ),
        migrations.AddField(
            model_name='expensepayment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='expensepayment',
            name='paid_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='expensepayment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='expense_payment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='expensepayment',
            constraint=models.UniqueConstraint(condition=models.Q(('reference', ''), _negated=True), fields=('organization', 'reference'), name='unique_expense_payment_reference_per_org'),
        ),
        migrations.RunPython(backfill_expense_approvals, migrations.RunPython.noop),
    ]
