# Generated by Django 5.0.14 on 2026-07-11 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_organization_options'),
        ('pos', '0002_cashmovement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='possession',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('organization', 'cashier', 'location'), name='unique_open_pos_session_per_cashier_location'),
        ),
    ]
