# Generated by Django 6.0.6 on 2026-08-14 23:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0009_agentprofile_verification_notes'),
        ('pos', '0004_offlineinvoicequeue_and_more'),
        ('sales', '0005_sale_unique_active_cart_per_session_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='offlineinvoicequeue',
            name='device_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='offlineinvoicequeue',
            name='draft_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recovery_drafts', to='sales.sale'),
        ),
        migrations.AddField(
            model_name='offlineinvoicequeue',
            name='payload_digest',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='offlineinvoicequeue',
            name='review_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='offlineinvoicequeue',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offlineinvoicequeue',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewed_offline_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offlineinvoicequeue',
            name='schema_version',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='offlineinvoicequeue',
            name='status',
            field=models.CharField(choices=[('queued', 'Review required'), ('processing', 'Under review'), ('completed', 'Reconciled'), ('failed', 'Conflict'), ('discarded', 'Discarded')], default='queued', max_length=20),
        ),
        migrations.AddIndex(
            model_name='offlineinvoicequeue',
            index=models.Index(fields=['organization', 'status', 'location', 'created_at'], name='pos_recovery_review_idx'),
        ),
    ]
