# Generated by Django 5.0.14 on 2026-07-11 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_invitation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ('name',), 'permissions': [('view_operational_report', 'Can view operational report'), ('view_retail_analytics', 'Can view retail analytics report'), ('view_activity_report', 'Can view activity report')]},
        ),
    ]
