# Generated by Django 5.0.14 on 2026-07-11 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_alter_organization_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='custodian_membership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='custody_locations', to='organizations.membership'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('warehouse', 'Warehouse'), ('pos', 'POS location'), ('agent', 'Agent custody'), ('in_transit', 'In transit'), ('repair', 'Repair')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='location',
            constraint=models.UniqueConstraint(condition=models.Q(('custodian_membership__isnull', False), ('is_active', True), ('location_type', 'agent')), fields=('organization', 'custodian_membership'), name='unique_active_agent_location_per_membership'),
        ),
    ]
