# Generated by Django 5.0.14 on 2026-07-11 22:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_location_custodian_membership_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_type', models.CharField(choices=[('agent', 'Agent'), ('dsa', 'Direct Sales Agent')], default='agent', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending verification'), ('active', 'Active'), ('suspended', 'Suspended'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('legal_name', models.CharField(max_length=255)),
                ('national_id_number', models.CharField(blank=True, max_length=80)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('registration_notes', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agent_profiles', to='organizations.branch')),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='agent_profile', to='organizations.membership')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization')),
                ('registered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='registered_agent_profiles', to=settings.AUTH_USER_MODEL)),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sub_agents', to='organizations.agentprofile')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='verified_agent_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('legal_name',),
            },
        ),
        migrations.AddConstraint(
            model_name='agentprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('national_id_number', ''), _negated=True), fields=('organization', 'national_id_number'), name='unique_agent_national_id_per_org'),
        ),
    ]
