# Generated by Django 5.0.14 on 2026-07-12 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0008_agentdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='verification_notes',
            field=models.TextField(blank=True),
        ),
    ]
