# Generated by Django 6.0.6 on 2026-08-14 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_emailoutbox'),
        ('operations', '0008_alter_approvalrequest_options_and_more'),
        ('organizations', '0009_agentprofile_verification_notes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='operations.approvalrequest'),
        ),
        migrations.AddField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('general', 'General update'), ('approval_request', 'Approval required'), ('approval_decision', 'Approval decision')], db_index=True, default='general', max_length=32),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['organization', 'recipient', 'read_at', 'created_at'], name='notify_inbox_idx'),
        ),
        migrations.AddConstraint(
            model_name='notification',
            constraint=models.UniqueConstraint(condition=models.Q(('approval__isnull', False)), fields=('recipient', 'approval', 'kind'), name='unique_approval_notification_recipient_kind'),
        ),
    ]
